#!/usr/bin/env bash
# Starts the real client under Xvfb, joins a flat test world (created by smoke-server.sh),
# gets a filled vape via a datapack, takes a puff with a simulated right click and prints
# small JPEG screenshots as base64 into the log (marked with ==SHOT name== ... ==END==).
set -u
export DISPLAY=:99
Xvfb :99 -screen 0 1280x720x24 >/tmp/xvfb.log 2>&1 &
sleep 2

# test world = the world generated by the dedicated server smoke test
mkdir -p run/saves
rm -rf run/saves/smoke
cp -r run/world run/saves/smoke
mkdir -p run/saves/smoke/datapacks/smoke/data/smoke/function run/saves/smoke/datapacks/smoke/data/minecraft/tags/function
cat > run/saves/smoke/datapacks/smoke/pack.mcmeta <<'JSON'
{ "pack": { "description": "vapemod smoke test", "min_format": [107, 1], "max_format": 200 } }
JSON
cat > run/saves/smoke/datapacks/smoke/data/minecraft/tags/function/tick.json <<'JSON'
{ "values": [ "smoke:tick" ] }
JSON
cat > run/saves/smoke/datapacks/smoke/data/smoke/function/tick.mcfunction <<'FN'
execute as @a[tag=!vape_given] run gamemode survival @s
execute as @a[tag=!vape_given] run item replace entity @s weapon.mainhand with vapemod:vape[vapemod:liquid={flavor:"mint",puffs:40,capacity:40}]
execute as @a[tag=!vape_given] run item replace entity @s weapon.offhand with vapemod:liquid_berry 3
execute as @a[tag=!vape_given] run time set noon
execute as @a[tag=!vape_given] run tp @s ~ ~ ~ 0 -10
tag @a add vape_given
FN

mkdir -p run/config
printf '[hud]\n\talwaysVisible = true\n' > run/config/vapemod-client.toml
printf 'onboardAccessibility:false\ntutorialStep:none\nskipMultiplayerWarning:true\njoinedFirstServer:true\npauseOnLostFocus:false\nrenderDistance:4\nsimulationDistance:5\nguiScale:2\nnarrator:0\nsoundCategory_master:0.0\n' > run/options.txt

( ./gradlew --no-configuration-cache runClient -PquickPlay=smoke > /tmp/client.log 2>&1; echo "exit=$?" >> /tmp/client.log ) &

shot() {
  import -window root /tmp/shot_full.png 2>/dev/null || return
  convert /tmp/shot_full.png -resize 640x360 -quality 70 /tmp/shot.jpg
  echo "==SHOT $1=="
  base64 -w 0 /tmp/shot.jpg
  echo
  echo "==END=="
}

joined=0
for i in $(seq 1 600); do
  if grep -q 'joined the game' /tmp/client.log; then joined=1; break; fi
  if grep -q '^exit=' /tmp/client.log; then break; fi
  sleep 1
done
echo "joined=$joined after ${i}s"
if [ $joined = 1 ]; then
  sleep 12
  shot hud
  xdotool mousemove 640 360 click 1 2>/dev/null; sleep 1
  xdotool mousedown 3; sleep 1.5
  shot inhale
  sleep 1.0
  xdotool mouseup 3; sleep 0.4
  shot exhale
  sleep 1.2
  shot after
  # hold longer than the max puff (3 s): the player must exhale automatically
  xdotool mousedown 3; sleep 3.4
  shot auto_exhale
  xdotool mouseup 3; sleep 1.5
  xdotool key F5; sleep 0.5
  xdotool mousedown 3; sleep 2.0; xdotool mouseup 3; sleep 0.3
  shot third_person
fi
pkill -f 'runClient' || true
pkill -f 'net.minecraftforge' || true
sleep 3
echo "=== client log (filtered) ==="
grep -E 'vapemod|VapeMod|Vape Mod|ERROR|Exception|Caused by|joined the game|OpenGL|Vulkan|GL_RENDERER|Backend|exit=' /tmp/client.log | grep -v 'DEBUG' | head -200
echo "=== mod warnings ==="
grep -E 'WARN|ERROR' /tmp/client.log | grep -E 'vapemod:' | head -50
echo "=== client log tail ==="
tail -40 /tmp/client.log
if [ $joined != 1 ]; then echo "Client did not join the world"; exit 1; fi
if grep -E '(ERROR|Exception).*' /tmp/client.log | grep -qE 'vapemod:|com\.example\.vapemod|co\.ex\.va\.'; then echo "Mod errors found"; exit 1; fi
if grep -E 'WARN|ERROR' /tmp/client.log | grep -E 'vapemod:' | grep -qiE 'missing|unable|failed|not found|unknown'; then echo "Missing mod resources"; exit 1; fi
echo "Client smoke test OK"
